/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IPv6AddressOrigin string

// List of IPv6AddressOrigin
const (
	STATIC IPv6AddressOrigin = "Static"
	DHC_PV6 IPv6AddressOrigin = "DHCPv6"
	LINK_LOCAL IPv6AddressOrigin = "LinkLocal"
	SLAAC IPv6AddressOrigin = "SLAAC"
)