/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ConnectedVia string

// List of ConnectedVia
const (
	NOT_CONNECTED ConnectedVia = "NotConnected"
	URI ConnectedVia = "URI"
	APPLET ConnectedVia = "Applet"
	OEM ConnectedVia = "Oem"
)