/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MediaType string

// List of MediaType
const (
	HDD MediaType = "HDD"
	SSD MediaType = "SSD"
	SMR MediaType = "SMR"
)