/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MediaType2 string

// List of MediaType_2
const (
	CD MediaType2 = "CD"
	FLOPPY MediaType2 = "Floppy"
	USB_STICK MediaType2 = "USBStick"
	DVD MediaType2 = "DVD"
)