/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type CommandConnectTypesSupported string

// List of CommandConnectTypesSupported
const (
	SSH CommandConnectTypesSupported = "SSH"
	TELNET CommandConnectTypesSupported = "Telnet"
	IPMI CommandConnectTypesSupported = "IPMI"
	OEM CommandConnectTypesSupported = "Oem"
)