/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The set of thresholds defined for a sensor.
type Thresholds struct {
	LowerCritical Threshold `json:"LowerCritical,omitempty"`
	LowerWarning Threshold `json:"LowerWarning,omitempty"`
	UpperCritical Threshold `json:"UpperCritical,omitempty"`
	UpperWarning Threshold `json:"UpperWarning,omitempty"`
}
