/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SecurityStates string

// List of SecurityStates
const (
	ENABLED SecurityStates = "Enabled"
	DISABLED SecurityStates = "Disabled"
	UNLOCKED SecurityStates = "Unlocked"
	LOCKED SecurityStates = "Locked"
	FROZEN SecurityStates = "Frozen"
	PASSPHRASELIMIT SecurityStates = "Passphraselimit"
)