/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AddressState string

// List of AddressState
const (
	PREFERRED AddressState = "Preferred"
	DEPRECATED AddressState = "Deprecated"
	TENTATIVE AddressState = "Tentative"
	FAILED AddressState = "Failed"
)