/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LinkNetworkTechnology string

// List of LinkNetworkTechnology
const (
	ETHERNET LinkNetworkTechnology = "Ethernet"
	INFINI_BAND LinkNetworkTechnology = "InfiniBand"
	FIBRE_CHANNEL LinkNetworkTechnology = "FibreChannel"
)