/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ResourceBlockType string

// List of ResourceBlockType
const (
	COMPUTE ResourceBlockType = "Compute"
	PROCESSOR ResourceBlockType = "Processor"
	MEMORY ResourceBlockType = "Memory"
	NETWORK ResourceBlockType = "Network"
	STORAGE ResourceBlockType = "Storage"
	COMPUTER_SYSTEM ResourceBlockType = "ComputerSystem"
	EXPANSION ResourceBlockType = "Expansion"
)