/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the definition for a PCI Interface object.
type PcIeInterface struct {
	// This is the number of PCIe lanes in use by this device.
	LanesInUse int32 `json:"LanesInUse,omitempty"`
	// This is the number of PCIe lanes supported by this device.
	MaxLanes int32 `json:"MaxLanes,omitempty"`
	MaxPCIeType PcIeTypes `json:"MaxPCIeType,omitempty"`
	// Oem extension object.
	Oem map[string]map[string]interface{} `json:"Oem,omitempty"`
	PCIeType PcIeTypes `json:"PCIeType,omitempty"`
}
