/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PowerSupplyType string

// List of PowerSupplyType
const (
	UNKNOWN PowerSupplyType = "Unknown"
	AC PowerSupplyType = "AC"
	DC PowerSupplyType = "DC"
	A_COR_DC PowerSupplyType = "ACorDC"
)