/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PowerState2 string

// List of PowerState_2
const (
	ON PowerState2 = "On"
	OFF PowerState2 = "Off"
	POWERING_ON PowerState2 = "PoweringOn"
	POWERING_OFF PowerState2 = "PoweringOff"
)