/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MemoryMirroring string

// List of MemoryMirroring
const (
	SYSTEM MemoryMirroring = "System"
	DIMM MemoryMirroring = "DIMM"
	HYBRID MemoryMirroring = "Hybrid"
	NONE MemoryMirroring = "None"
)