/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type DurableNameFormat string

// List of DurableNameFormat
const (
	NAA DurableNameFormat = "NAA"
	I_QN DurableNameFormat = "iQN"
	FC_WWN DurableNameFormat = "FC_WWN"
	UUID DurableNameFormat = "UUID"
	EUI DurableNameFormat = "EUI"
)