/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type CalculationAlgorithmEnum string

// List of CalculationAlgorithmEnum
const (
	AVERAGE CalculationAlgorithmEnum = "Average"
	MAXIMUM CalculationAlgorithmEnum = "Maximum"
	MINIMUM CalculationAlgorithmEnum = "Minimum"
)