/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type NotifyIPv6Scope string

// List of NotifyIPv6Scope
const (
	LINK NotifyIPv6Scope = "Link"
	SITE NotifyIPv6Scope = "Site"
	ORGANIZATION NotifyIPv6Scope = "Organization"
)