/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IpAddressType string

// List of IPAddressType
const (
	I_PV4 IpAddressType = "IPv4"
	I_PV6 IpAddressType = "IPv6"
)