/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AddressRangeType string

// List of AddressRangeType
const (
	VOLATILE AddressRangeType = "Volatile"
	PMEM AddressRangeType = "PMEM"
	BLOCK AddressRangeType = "Block"
)