/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AuthenticationTypes string

// List of AuthenticationTypes
const (
	TOKEN AuthenticationTypes = "Token"
	KERBEROS_KEYTAB AuthenticationTypes = "KerberosKeytab"
	USERNAME_AND_PASSWORD AuthenticationTypes = "UsernameAndPassword"
	OEM AuthenticationTypes = "OEM"
)