/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MetricDataType : The data type of the related metric values.  The property provides information to the client on the nature of the metric reading.
type MetricDataType string

// List of MetricDataType
const (
	BOOLEAN MetricDataType = "Boolean"
	DATE_TIME MetricDataType = "DateTime"
	DECIMAL MetricDataType = "Decimal"
	INTEGER MetricDataType = "Integer"
	STRING MetricDataType = "String"
	ENUMERATION MetricDataType = "Enumeration"
)