/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IndicatorLed string

// List of IndicatorLED
const (
	UNKNOWN IndicatorLed = "Unknown"
	LIT IndicatorLed = "Lit"
	BLINKING IndicatorLed = "Blinking"
	OFF IndicatorLed = "Off"
)