/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SlotTypes string

// List of SlotTypes
const (
	FULL_LENGTH SlotTypes = "FullLength"
	HALF_LENGTH SlotTypes = "HalfLength"
	LOW_PROFILE SlotTypes = "LowProfile"
	MINI SlotTypes = "Mini"
	M2 SlotTypes = "M2"
	OEM SlotTypes = "OEM"
)