/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SecureBootModeType string

// List of SecureBootModeType
const (
	SETUP_MODE SecureBootModeType = "SetupMode"
	USER_MODE SecureBootModeType = "UserMode"
	AUDIT_MODE SecureBootModeType = "AuditMode"
	DEPLOYED_MODE SecureBootModeType = "DeployedMode"
)