/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type NetworkDeviceTechnology string

// List of NetworkDeviceTechnology
const (
	DISABLED NetworkDeviceTechnology = "Disabled"
	ETHERNET NetworkDeviceTechnology = "Ethernet"
	FIBRE_CHANNEL NetworkDeviceTechnology = "FibreChannel"
	I_SCSI NetworkDeviceTechnology = "iSCSI"
	FIBRE_CHANNEL_OVER_ETHERNET NetworkDeviceTechnology = "FibreChannelOverEthernet"
)