/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IndicatorLed2 string

// List of IndicatorLED_2
const (
	UNKNOWN IndicatorLed2 = "Unknown"
	LIT IndicatorLed2 = "Lit"
	BLINKING IndicatorLed2 = "Blinking"
	OFF IndicatorLed2 = "Off"
)