/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type InputType string

// List of InputType
const (
	AC InputType = "AC"
	DC InputType = "DC"
)