/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type Parity string

// List of Parity
const (
	NONE Parity = "None"
	EVEN Parity = "Even"
	ODD Parity = "Odd"
	MARK Parity = "Mark"
	SPACE Parity = "Space"
)