/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains references to other resources that are related to this resource.
type Volume2Links struct {
	// An array of references to the drives which contain this volume. This will reference Drives that either wholly or only partly contain this volume.
	Drives []IdRef `json:"Drives,omitempty"`
	// The number of items in a collection.
	DrivesodataCount float32 `json:"Drives@odata.count,omitempty"`
	DrivesodataNavigationLink string `json:"Drives@odata.navigationLink,omitempty"`
	// Oem extension object.
	Oem map[string]map[string]interface{} `json:"Oem,omitempty"`
}
