/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains references to other resources that are related to this resource.
type Links2 struct {
	// Oem extension object.
	Oem map[string]map[string]interface{} `json:"Oem,omitempty"`
	Role IdRef `json:"Role,omitempty"`
}
