/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SupportedEthernetCapabilities string

// List of SupportedEthernetCapabilities
const (
	WAKE_ON_LAN SupportedEthernetCapabilities = "WakeOnLAN"
	EEE SupportedEthernetCapabilities = "EEE"
)