/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EventType string

// List of EventType
const (
	STATUS_CHANGE EventType = "StatusChange"
	RESOURCE_UPDATED EventType = "ResourceUpdated"
	RESOURCE_ADDED EventType = "ResourceAdded"
	RESOURCE_REMOVED EventType = "ResourceRemoved"
	ALERT EventType = "Alert"
	METRIC_REPORT EventType = "MetricReport"
)