/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PcIeTypes string

// List of PCIeTypes
const (
	GEN1 PcIeTypes = "Gen1"
	GEN2 PcIeTypes = "Gen2"
	GEN3 PcIeTypes = "Gen3"
	GEN4 PcIeTypes = "Gen4"
	GEN5 PcIeTypes = "Gen5"
)