/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type contains security capabilities of a Memory entity.
type SecurityCapabilities struct {
	// Maximum number of passphrases supported for this Memory.
	MaxPassphraseCount int32 `json:"MaxPassphraseCount,omitempty"`
	// Memory passphrase set capability.
	PassphraseCapable bool `json:"PassphraseCapable,omitempty"`
	// Security states supported by the Memory.
	SecurityStates []SecurityStates `json:"SecurityStates,omitempty"`
}
