/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReportActionsEnum : Actions to perform when a metric report is generated.
type ReportActionsEnum string

// List of ReportActionsEnum
const (
	LOG_TO_METRIC_REPORTS_COLLECTION ReportActionsEnum = "LogToMetricReportsCollection"
	REDFISH_EVENT ReportActionsEnum = "RedfishEvent"
)