/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// An Event Destination desribes the target of an event subscription, including the types of events subscribed and context to provide to the target in the Event payload.
type EventDestination2 struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// A client-supplied string that is stored with the event destination subscription.
	Context string `json:"Context"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// The URI of the destination Event Service.
	Destination string `json:"Destination,omitempty"`
	EventFormatType EventFormatType `json:"EventFormatType,omitempty"`
	// This property contains the types of events that will be sent to the desination.
	EventTypes []EventType `json:"EventTypes,omitempty"`
	// This is for setting HTTP headers, such as authorization information.  This object will be null on a GET.
	HttpHeaders []map[string]interface{} `json:"HttpHeaders,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// A list of MessageIds that the service will only send.  If this property is absent or the array is empty, then Events with any MessageId will be sent to the subscriber.
	MessageIds []string `json:"MessageIds,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	// Oem extension object.
	Oem map[string]map[string]interface{} `json:"Oem,omitempty"`
	// A list of resources for which the service will only send related events.  If this property is absent or the array is empty, then Events originating from any resource will be sent to the subscriber.
	OriginResources []IdRef `json:"OriginResources,omitempty"`
	// The number of items in a collection.
	OriginResourcesodataCount int32 `json:"OriginResources@odata.count,omitempty"`
	Protocol EventDestinationProtocol `json:"Protocol,omitempty"`
	// A list of the Prefixes for the Message Registries that contain the MessageIds that will be sent to this event destination.
	RegistryPrefixes []string `json:"RegistryPrefixes,omitempty"`
	// A list of Resource Type values (Schema names) that correspond to the OriginOfCondition.  The version and full namespace should not be specified.
	ResourceTypes []string `json:"ResourceTypes,omitempty"`
	// By setting this to true and specifying OriginResources, this indicates the subscription will be for events from the OriginsResources specified and also all subordinate resources.  Note that resources associated via the Links section are not considered subordinate.
	SubordinateResources bool `json:"SubordinateResources,omitempty"`
	SubscriptionType SubscriptionType `json:"SubscriptionType"`
}
