/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type DataBits string

// List of DataBits
const (
	_5 DataBits = "5"
	_6 DataBits = "6"
	_7 DataBits = "7"
	_8 DataBits = "8"
)