/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ErrorCorrection string

// List of ErrorCorrection
const (
	NO_ECC ErrorCorrection = "NoECC"
	SINGLE_BIT_ECC ErrorCorrection = "SingleBitECC"
	MULTI_BIT_ECC ErrorCorrection = "MultiBitECC"
	ADDRESS_PARITY ErrorCorrection = "AddressParity"
)