/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EncryptionStatus string

// List of EncryptionStatus
const (
	UNECRYPTED EncryptionStatus = "Unecrypted"
	UNLOCKED EncryptionStatus = "Unlocked"
	LOCKED EncryptionStatus = "Locked"
	FOREIGN EncryptionStatus = "Foreign"
	UNENCRYPTED EncryptionStatus = "Unencrypted"
)