/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MetricReportDefinitionType : Indicates when the metric report is generated.
type MetricReportDefinitionType string

// List of MetricReportDefinitionType
const (
	PERIODIC MetricReportDefinitionType = "Periodic"
	ON_CHANGE MetricReportDefinitionType = "OnChange"
	ON_REQUEST MetricReportDefinitionType = "OnRequest"
)