/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type VolumeType string

// List of VolumeType
const (
	RAW_DEVICE VolumeType = "RawDevice"
	NON_REDUNDANT VolumeType = "NonRedundant"
	MIRRORED VolumeType = "Mirrored"
	STRIPED_WITH_PARITY VolumeType = "StripedWithParity"
	SPANNED_MIRRORS VolumeType = "SpannedMirrors"
	SPANNED_STRIPES_WITH_PARITY VolumeType = "SpannedStripesWithParity"
)