/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Volume contains properties used to describe a volume, virtual disk, LUN, or other logical storage entity for any system.
type Volume struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id,omitempty"`
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The type of a resource.
	OdataType string `json:"@odata.type,omitempty"`
	Actions Volume2Actions `json:"Actions,omitempty"`
	// The size of the smallest addressible unit (Block) of this volume in bytes.
	BlockSizeBytes float32 `json:"BlockSizeBytes,omitempty"`
	// The size in bytes of this Volume.
	CapacityBytes float32 `json:"CapacityBytes,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Is this Volume encrypted.
	Encrypted bool `json:"Encrypted,omitempty"`
	// The types of encryption used by this Volume.
	EncryptionTypes []EncryptionTypes `json:"EncryptionTypes,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// The Durable names for the volume.
	Identifiers []Identifier2 `json:"Identifiers,omitempty"`
	Links Volume2Links `json:"Links,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	// Oem extension object.
	Oem map[string]map[string]interface{} `json:"Oem,omitempty"`
	// The operations currently running on the Volume.
	Operations []Operations2 `json:"Operations,omitempty"`
	// The size in bytes of this Volume's optimum IO size.
	OptimumIOSizeBytes float32 `json:"OptimumIOSizeBytes,omitempty"`
	Status Status `json:"Status,omitempty"`
	VolumeType VolumeType `json:"VolumeType,omitempty"`
}
