/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EncryptionAbility string

// List of EncryptionAbility
const (
	NONE EncryptionAbility = "None"
	SELF_ENCRYPTING_DRIVE EncryptionAbility = "SelfEncryptingDrive"
	OTHER EncryptionAbility = "Other"
)