/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type FlowControl2 string

// List of FlowControl_2
const (
	NONE FlowControl2 = "None"
	SOFTWARE FlowControl2 = "Software"
	HARDWARE FlowControl2 = "Hardware"
)