/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This an interleave set for a memory chunk.
type InterleaveSet struct {
	Memory IdRef `json:"Memory,omitempty"`
	// Level of the interleave set for multi-level tiered memory.
	MemoryLevel int32 `json:"MemoryLevel,omitempty"`
	// Offset within the DIMM that corresponds to the start of this memory region, measured in mebibytes (MiB).
	OffsetMiB int32 `json:"OffsetMiB,omitempty"`
	// DIMM region identifier.
	RegionId string `json:"RegionId,omitempty"`
	// Size of this memory region measured in mebibytes (MiB).
	SizeMiB int32 `json:"SizeMiB,omitempty"`
}
