/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// HostingRole : The enumerations of HostingRoles specify different features that the hosting ComputerSystem supports.
type HostingRole string

// List of HostingRole
const (
	APPLICATION_SERVER HostingRole = "ApplicationServer"
	STORAGE_SERVER HostingRole = "StorageServer"
	SWITCH HostingRole = "Switch"
)