/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AuthenticationMethod string

// List of AuthenticationMethod
const (
	NONE AuthenticationMethod = "None"
	CHAP AuthenticationMethod = "CHAP"
	MUTUAL_CHAP AuthenticationMethod = "MutualCHAP"
)