/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CollectionFunction : An operation to perform over the sample.
type CollectionFunction string

// List of CollectionFunction
const (
	AVERAGE CollectionFunction = "Average"
	MAXIMUM CollectionFunction = "Maximum"
	MINIMUM CollectionFunction = "Minimum"
	SUMMATION CollectionFunction = "Summation"
)