/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PinOut string

// List of PinOut
const (
	CISCO PinOut = "Cisco"
	CYCLADES PinOut = "Cyclades"
	DIGI PinOut = "Digi"
)