/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PowerLimitException string

// List of PowerLimitException
const (
	NO_ACTION PowerLimitException = "NoAction"
	HARD_POWER_OFF PowerLimitException = "HardPowerOff"
	LOG_EVENT_ONLY PowerLimitException = "LogEventOnly"
	OEM PowerLimitException = "Oem"
)