/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EntityType string

// List of EntityType
const (
	STORAGE_INITIATOR EntityType = "StorageInitiator"
	ROOT_COMPLEX EntityType = "RootComplex"
	NETWORK_CONTROLLER EntityType = "NetworkController"
	DRIVE EntityType = "Drive"
	STORAGE_EXPANDER EntityType = "StorageExpander"
	DISPLAY_CONTROLLER EntityType = "DisplayController"
	BRIDGE EntityType = "Bridge"
	PROCESSOR EntityType = "Processor"
	VOLUME EntityType = "Volume"
)