/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type StatusIndicator string

// List of StatusIndicator
const (
	OK StatusIndicator = "OK"
	FAIL StatusIndicator = "Fail"
	REBUILD StatusIndicator = "Rebuild"
	PREDICTIVE_FAILURE_ANALYSIS StatusIndicator = "PredictiveFailureAnalysis"
	HOTSPARE StatusIndicator = "Hotspare"
	IN_A_CRITICAL_ARRAY StatusIndicator = "InACriticalArray"
	IN_A_FAILED_ARRAY StatusIndicator = "InAFailedArray"
)