/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type StopBits string

// List of StopBits
const (
	_1 StopBits = "1"
	_2 StopBits = "2"
)