/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type DhcPv6OperatingMode string

// List of DHCPv6OperatingMode
const (
	STATEFUL DhcPv6OperatingMode = "Stateful"
	STATELESS DhcPv6OperatingMode = "Stateless"
	DISABLED DhcPv6OperatingMode = "Disabled"
)