/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ManagerType string

// List of ManagerType
const (
	MANAGEMENT_CONTROLLER ManagerType = "ManagementController"
	ENCLOSURE_MANAGER ManagerType = "EnclosureManager"
	BMC ManagerType = "BMC"
	RACK_MANAGER ManagerType = "RackManager"
	AUXILIARY_CONTROLLER ManagerType = "AuxiliaryController"
	SERVICE ManagerType = "Service"
)