/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PortType string

// List of PortType
const (
	UPSTREAM_PORT PortType = "UpstreamPort"
	DOWNSTREAM_PORT PortType = "DownstreamPort"
	INTERSWITCH_PORT PortType = "InterswitchPort"
	MANAGEMENT_PORT PortType = "ManagementPort"
	BIDIRECTIONAL_PORT PortType = "BidirectionalPort"
	UNCONFIGURED_PORT PortType = "UnconfiguredPort"
)