/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type BitRate string

// List of BitRate
const (
	_1200 BitRate = "1200"
	_2400 BitRate = "2400"
	_4800 BitRate = "4800"
	_9600 BitRate = "9600"
	_19200 BitRate = "19200"
	_38400 BitRate = "38400"
	_57600 BitRate = "57600"
	_115200 BitRate = "115200"
	_230400 BitRate = "230400"
)