/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ProcessorArchitecture string

// List of ProcessorArchitecture
const (
	X86 ProcessorArchitecture = "x86"
	IA_64 ProcessorArchitecture = "IA-64"
	ARM ProcessorArchitecture = "ARM"
	MIPS ProcessorArchitecture = "MIPS"
	OEM ProcessorArchitecture = "OEM"
)