/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DiscreteTriggerConditionEnum : Specifies the condition, in relationship to the discrete trigger values, which constitutes a trigger.
type DiscreteTriggerConditionEnum string

// List of DiscreteTriggerConditionEnum
const (
	SPECIFIED DiscreteTriggerConditionEnum = "Specified"
	CHANGED DiscreteTriggerConditionEnum = "Changed"
)