/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PortConnectionType string

// List of PortConnectionType
const (
	NOT_CONNECTED PortConnectionType = "NotConnected"
	N_PORT PortConnectionType = "NPort"
	POINT_TO_POINT PortConnectionType = "PointToPoint"
	PRIVATE_LOOP PortConnectionType = "PrivateLoop"
	PUBLIC_LOOP PortConnectionType = "PublicLoop"
	GENERIC PortConnectionType = "Generic"
	EXTENDER_FABRIC PortConnectionType = "ExtenderFabric"
)