/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SerialConnectTypesSupported string

// List of SerialConnectTypesSupported
const (
	SSH SerialConnectTypesSupported = "SSH"
	TELNET SerialConnectTypesSupported = "Telnet"
	IPMI SerialConnectTypesSupported = "IPMI"
	OEM SerialConnectTypesSupported = "Oem"
)