/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MemoryMedia string

// List of MemoryMedia
const (
	DRAM MemoryMedia = "DRAM"
	NAND MemoryMedia = "NAND"
	PROPRIETARY MemoryMedia = "Proprietary"
)