/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AuthenticationMode string

// List of AuthenticationMode
const (
	AUTH_NONE AuthenticationMode = "AuthNone"
	BASIC_AUTH AuthenticationMode = "BasicAuth"
	REDFISH_SESSION_AUTH AuthenticationMode = "RedfishSessionAuth"
	OEM_AUTH AuthenticationMode = "OemAuth"
)