/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A network controller ASIC that makes up part of a NetworkAdapter.
type Controllers struct {
	ControllerCapabilities ControllerCapabilities `json:"ControllerCapabilities,omitempty"`
	// The version of the user-facing firmware package.
	FirmwarePackageVersion string `json:"FirmwarePackageVersion,omitempty"`
	Links ControllerLinks `json:"Links,omitempty"`
	Location Location2 `json:"Location,omitempty"`
	PCIeInterface PcIeInterface2 `json:"PCIeInterface,omitempty"`
}
