/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AccountProviderTypes string

// List of AccountProviderTypes
const (
	REDFISH_SERVICE AccountProviderTypes = "RedfishService"
	ACTIVE_DIRECTORY_SERVICE AccountProviderTypes = "ActiveDirectoryService"
	LDAP_SERVICE AccountProviderTypes = "LDAPService"
	OEM AccountProviderTypes = "OEM"
)