/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type OverWritePolicy string

// List of OverWritePolicy
const (
	UNKNOWN OverWritePolicy = "Unknown"
	WRAPS_WHEN_FULL OverWritePolicy = "WrapsWhenFull"
	NEVER_OVER_WRITES OverWritePolicy = "NeverOverWrites"
)