/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ReadingUnits string

// List of ReadingUnits
const (
	RPM ReadingUnits = "RPM"
	PERCENT ReadingUnits = "Percent"
)