/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SystemType string

// List of SystemType
const (
	PHYSICAL SystemType = "Physical"
	VIRTUAL SystemType = "Virtual"
	OS SystemType = "OS"
	PHYSICALLY_PARTITIONED SystemType = "PhysicallyPartitioned"
	VIRTUALLY_PARTITIONED SystemType = "VirtuallyPartitioned"
	COMPOSED SystemType = "Composed"
)