/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type CompositionState string

// List of CompositionState
const (
	COMPOSING CompositionState = "Composing"
	COMPOSED_AND_AVAILABLE CompositionState = "ComposedAndAvailable"
	COMPOSED CompositionState = "Composed"
	UNUSED CompositionState = "Unused"
	FAILED CompositionState = "Failed"
	UNAVAILABLE CompositionState = "Unavailable"
)