/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type OverWritePolicy2 string

// List of OverWritePolicy_2
const (
	MANUAL OverWritePolicy2 = "Manual"
	OLDEST OverWritePolicy2 = "Oldest"
)