/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MetricType : Specifies the type of metric provided.  The property provides information to the client on how the metric can be handled.
type MetricType string

// List of MetricType
const (
	NUMERIC MetricType = "Numeric"
	DISCRETE MetricType = "Discrete"
	GAUGE MetricType = "Gauge"
	COUNTER MetricType = "Counter"
	COUNTDOWN MetricType = "Countdown"
)