/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MemoryClassification string

// List of MemoryClassification
const (
	VOLATILE MemoryClassification = "Volatile"
	BYTE_ACCESSIBLE_PERSISTENT MemoryClassification = "ByteAccessiblePersistent"
	BLOCK MemoryClassification = "Block"
)