/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type HotspareReplacementModeType string

// List of HotspareReplacementModeType
const (
	REVERTIBLE HotspareReplacementModeType = "Revertible"
	NON_REVERTIBLE HotspareReplacementModeType = "NonRevertible"
)