/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LogEntryType string

// List of LogEntryType
const (
	EVENT LogEntryType = "Event"
	SEL LogEntryType = "SEL"
	OEM LogEntryType = "Oem"
)