/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This action is used to prepare the contents of the volume for use by the system.
type Initialize struct {
	// Link to invoke action
	Target string `json:"target,omitempty"`
	// Friendly action name
	Title string `json:"title,omitempty"`
}
