/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// A metric Value.
type MetricValue struct {
	MetricDefinition IdRef `json:"MetricDefinition,omitempty"`
	// The metric definitions identifier for this metric.
	MetricId string `json:"MetricId,omitempty"`
	// The URI for the property from which this metric is derived.
	MetricProperty string `json:"MetricProperty,omitempty"`
	// The value identifies this resource.
	MetricValue string `json:"MetricValue,omitempty"`
	// The time when the value of the metric is obtained.
	Timestamp time.Time `json:"Timestamp,omitempty"`
}
