/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EventSeverity string

// List of EventSeverity
const (
	OK EventSeverity = "OK"
	WARNING EventSeverity = "Warning"
	CRITICAL EventSeverity = "Critical"
)