/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ConnectorType string

// List of ConnectorType
const (
	RJ45 ConnectorType = "RJ45"
	RJ11 ConnectorType = "RJ11"
	DB9_FEMALE ConnectorType = "DB9 Female"
	DB9_MALE ConnectorType = "DB9 Male"
	DB25_FEMALE ConnectorType = "DB25 Female"
	DB25_MALE ConnectorType = "DB25 Male"
	USB ConnectorType = "USB"
	M_USB ConnectorType = "mUSB"
	U_USB ConnectorType = "uUSB"
)