/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type BootSourceOverrideEnabled string

// List of BootSourceOverrideEnabled
const (
	DISABLED BootSourceOverrideEnabled = "Disabled"
	ONCE BootSourceOverrideEnabled = "Once"
	CONTINUOUS BootSourceOverrideEnabled = "Continuous"
)