/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LogEntryCode string

// List of LogEntryCode
const (
	ASSERT LogEntryCode = "Assert"
	DEASSERT LogEntryCode = "Deassert"
	LOWER_NON_CRITICAL___GOING_LOW LogEntryCode = "Lower Non-critical - going low"
	LOWER_NON_CRITICAL___GOING_HIGH LogEntryCode = "Lower Non-critical - going high"
	LOWER_CRITICAL___GOING_LOW LogEntryCode = "Lower Critical - going low"
	LOWER_CRITICAL___GOING_HIGH LogEntryCode = "Lower Critical - going high"
	LOWER_NON_RECOVERABLE___GOING_LOW LogEntryCode = "Lower Non-recoverable - going low"
	LOWER_NON_RECOVERABLE___GOING_HIGH LogEntryCode = "Lower Non-recoverable - going high"
	UPPER_NON_CRITICAL___GOING_LOW LogEntryCode = "Upper Non-critical - going low"
	UPPER_NON_CRITICAL___GOING_HIGH LogEntryCode = "Upper Non-critical - going high"
	UPPER_CRITICAL___GOING_LOW LogEntryCode = "Upper Critical - going low"
	UPPER_CRITICAL___GOING_HIGH LogEntryCode = "Upper Critical - going high"
	UPPER_NON_RECOVERABLE___GOING_LOW LogEntryCode = "Upper Non-recoverable - going low"
	UPPER_NON_RECOVERABLE___GOING_HIGH LogEntryCode = "Upper Non-recoverable - going high"
	TRANSITION_TO_IDLE LogEntryCode = "Transition to Idle"
	TRANSITION_TO_ACTIVE LogEntryCode = "Transition to Active"
	TRANSITION_TO_BUSY LogEntryCode = "Transition to Busy"
	STATE_DEASSERTED LogEntryCode = "State Deasserted"
	STATE_ASSERTED LogEntryCode = "State Asserted"
	PREDICTIVE_FAILURE_DEASSERTED LogEntryCode = "Predictive Failure deasserted"
	PREDICTIVE_FAILURE_ASSERTED LogEntryCode = "Predictive Failure asserted"
	LIMIT_NOT_EXCEEDED LogEntryCode = "Limit Not Exceeded"
	LIMIT_EXCEEDED LogEntryCode = "Limit Exceeded"
	PERFORMANCE_MET LogEntryCode = "Performance Met"
	PERFORMANCE_LAGS LogEntryCode = "Performance Lags"
	TRANSITION_TO_OK LogEntryCode = "Transition to OK"
	TRANSITION_TO_NON_CRITICAL_FROM_OK LogEntryCode = "Transition to Non-Critical from OK"
	TRANSITION_TO_CRITICAL_FROM_LESS_SEVERE LogEntryCode = "Transition to Critical from less severe"
	TRANSITION_TO_NON_RECOVERABLE_FROM_LESS_SEVERE LogEntryCode = "Transition to Non-recoverable from less severe"
	TRANSITION_TO_NON_CRITICAL_FROM_MORE_SEVERE LogEntryCode = "Transition to Non-Critical from more severe"
	TRANSITION_TO_CRITICAL_FROM_NON_RECOVERABLE LogEntryCode = "Transition to Critical from Non-recoverable"
	TRANSITION_TO_NON_RECOVERABLE LogEntryCode = "Transition to Non-recoverable"
	MONITOR LogEntryCode = "Monitor"
	INFORMATIONAL LogEntryCode = "Informational"
	DEVICE_REMOVED__DEVICE_ABSENT LogEntryCode = "Device Removed / Device Absent"
	DEVICE_INSERTED__DEVICE_PRESENT LogEntryCode = "Device Inserted / Device Present"
	DEVICE_DISABLED LogEntryCode = "Device Disabled"
	DEVICE_ENABLED LogEntryCode = "Device Enabled"
	TRANSITION_TO_RUNNING LogEntryCode = "Transition to Running"
	TRANSITION_TO_IN_TEST LogEntryCode = "Transition to In Test"
	TRANSITION_TO_POWER_OFF LogEntryCode = "Transition to Power Off"
	TRANSITION_TO_ON_LINE LogEntryCode = "Transition to On Line"
	TRANSITION_TO_OFF_LINE LogEntryCode = "Transition to Off Line"
	TRANSITION_TO_OFF_DUTY LogEntryCode = "Transition to Off Duty"
	TRANSITION_TO_DEGRADED LogEntryCode = "Transition to Degraded"
	TRANSITION_TO_POWER_SAVE LogEntryCode = "Transition to Power Save"
	INSTALL_ERROR LogEntryCode = "Install Error"
	FULLY_REDUNDANT LogEntryCode = "Fully Redundant"
	REDUNDANCY_LOST LogEntryCode = "Redundancy Lost"
	REDUNDANCY_DEGRADED LogEntryCode = "Redundancy Degraded"
	NON_REDUNDANTSUFFICIENT_RESOURCES_FROM_REDUNDANT LogEntryCode = "Non-redundant:Sufficient Resources from Redundant"
	NON_REDUNDANTSUFFICIENT_RESOURCES_FROM_INSUFFICIENT_RESOURCES LogEntryCode = "Non-redundant:Sufficient Resources from Insufficient Resources"
	NON_REDUNDANTINSUFFICIENT_RESOURCES LogEntryCode = "Non-redundant:Insufficient Resources"
	REDUNDANCY_DEGRADED_FROM_FULLY_REDUNDANT LogEntryCode = "Redundancy Degraded from Fully Redundant"
	REDUNDANCY_DEGRADED_FROM_NON_REDUNDANT LogEntryCode = "Redundancy Degraded from Non-redundant"
	D0_POWER_STATE LogEntryCode = "D0 Power State"
	D1_POWER_STATE LogEntryCode = "D1 Power State"
	D2_POWER_STATE LogEntryCode = "D2 Power State"
	D3_POWER_STATE LogEntryCode = "D3 Power State"
	OEM LogEntryCode = "OEM"
)