/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LocalAccountAuth string

// List of LocalAccountAuth
const (
	ENABLED LocalAccountAuth = "Enabled"
	DISABLED LocalAccountAuth = "Disabled"
	FALLBACK LocalAccountAuth = "Fallback"
)