/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type TransferProtocolType string

// List of TransferProtocolType
const (
	CIFS TransferProtocolType = "CIFS"
	FTP TransferProtocolType = "FTP"
	SFTP TransferProtocolType = "SFTP"
	HTTP TransferProtocolType = "HTTP"
	HTTPS TransferProtocolType = "HTTPS"
	NSF TransferProtocolType = "NSF"
	SCP TransferProtocolType = "SCP"
	TFTP TransferProtocolType = "TFTP"
	OEM TransferProtocolType = "OEM"
	NFS TransferProtocolType = "NFS"
)