/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LogEntryTypes string

// List of LogEntryTypes
const (
	EVENT LogEntryTypes = "Event"
	SEL LogEntryTypes = "SEL"
	MULTIPLE LogEntryTypes = "Multiple"
	OEM LogEntryTypes = "OEM"
)