/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type FlowControl string

// List of FlowControl
const (
	NONE FlowControl = "None"
	TX FlowControl = "TX"
	RX FlowControl = "RX"
	TX_RX FlowControl = "TX_RX"
)