/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SignalType string

// List of SignalType
const (
	RS232 SignalType = "Rs232"
	RS485 SignalType = "Rs485"
)