/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the schema definition for the Processor resource.  It represents the properties of a processor attached to a System.
type Processor struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	Assembly IdRef `json:"Assembly,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	InstructionSet InstructionSet `json:"InstructionSet,omitempty"`
	Links Links2 `json:"Links,omitempty"`
	Location Location2 `json:"Location,omitempty"`
	// The processor manufacturer.
	Manufacturer string `json:"Manufacturer,omitempty"`
	// The maximum clock speed of the processor.
	MaxSpeedMHz int32 `json:"MaxSpeedMHz,omitempty"`
	// The product model number of this device.
	Model string `json:"Model,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	// Oem extension object.
	Oem map[string]map[string]interface{} `json:"Oem,omitempty"`
	ProcessorArchitecture ProcessorArchitecture `json:"ProcessorArchitecture,omitempty"`
	ProcessorId ProcessorId `json:"ProcessorId,omitempty"`
	ProcessorType ProcessorType `json:"ProcessorType,omitempty"`
	// The socket or location of the processor.
	Socket string `json:"Socket,omitempty"`
	Status Status `json:"Status,omitempty"`
	SubProcessors IdRef `json:"SubProcessors,omitempty"`
	// The total number of cores contained in this processor.
	TotalCores int32 `json:"TotalCores,omitempty"`
	// The total number of execution threads supported by this processor.
	TotalThreads int32 `json:"TotalThreads,omitempty"`
}
