/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type TaskState string

// List of TaskState
const (
	NEW TaskState = "New"
	STARTING TaskState = "Starting"
	RUNNING TaskState = "Running"
	SUSPENDED TaskState = "Suspended"
	INTERRUPTED TaskState = "Interrupted"
	PENDING TaskState = "Pending"
	STOPPING TaskState = "Stopping"
	COMPLETED TaskState = "Completed"
	KILLED TaskState = "Killed"
	EXCEPTION TaskState = "Exception"
	SERVICE TaskState = "Service"
	CANCELLING TaskState = "Cancelling"
	CANCELLED TaskState = "Cancelled"
)