/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EventDestinationProtocol string

// List of EventDestinationProtocol
const (
	REDFISH EventDestinationProtocol = "Redfish"
)