/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ProcessorType string

// List of ProcessorType
const (
	CPU ProcessorType = "CPU"
	GPU ProcessorType = "GPU"
	FPGA ProcessorType = "FPGA"
	DSP ProcessorType = "DSP"
	ACCELERATOR ProcessorType = "Accelerator"
	CORE ProcessorType = "Core"
	THREAD ProcessorType = "Thread"
	OEM ProcessorType = "OEM"
)