/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type BootSourceOverrideMode string

// List of BootSourceOverrideMode
const (
	LEGACY BootSourceOverrideMode = "Legacy"
	UEFI BootSourceOverrideMode = "UEFI"
)