/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ThresholdActivation string

// List of ThresholdActivation
const (
	INCREASING ThresholdActivation = "Increasing"
	DECREASING ThresholdActivation = "Decreasing"
	EITHER ThresholdActivation = "Either"
)