/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EventFormatType string

// List of EventFormatType
const (
	EVENT EventFormatType = "Event"
	METRIC_REPORT EventFormatType = "MetricReport"
)