/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ImplementationType string

// List of ImplementationType
const (
	PHYSICAL_SENSOR ImplementationType = "PhysicalSensor"
	CALCULATED ImplementationType = "Calculated"
	SYNTHESIZED ImplementationType = "Synthesized"
	DIGITAL_METER ImplementationType = "DigitalMeter"
)