/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type HotspareType string

// List of HotspareType
const (
	NONE HotspareType = "None"
	GLOBAL HotspareType = "Global"
	CHASSIS HotspareType = "Chassis"
	DEDICATED HotspareType = "Dedicated"
)