/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MemoryType string

// List of MemoryType
const (
	DRAM MemoryType = "DRAM"
	NVDIMM_N MemoryType = "NVDIMM_N"
	NVDIMM_F MemoryType = "NVDIMM_F"
	NVDIMM_P MemoryType = "NVDIMM_P"
	INTEL_OPTANE MemoryType = "IntelOptane"
)