/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ResetKeysType string

// List of ResetKeysType
const (
	RESET_ALL_KEYS_TO_DEFAULT ResetKeysType = "ResetAllKeysToDefault"
	DELETE_ALL_KEYS ResetKeysType = "DeleteAllKeys"
	DELETE_PK ResetKeysType = "DeletePK"
)