/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains settings for parsing a generic LDAP service.
type LdapService struct {
	// Oem extension object.
	Oem map[string]map[string]interface{} `json:"Oem,omitempty"`
	SearchSettings LdapSearchSettings `json:"SearchSettings,omitempty"`
}
