/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EntityRole string

// List of EntityRole
const (
	INITIATOR EntityRole = "Initiator"
	TARGET EntityRole = "Target"
	BOTH EntityRole = "Both"
)