/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type DeviceType string

// List of DeviceType
const (
	SINGLE_FUNCTION DeviceType = "SingleFunction"
	MULTI_FUNCTION DeviceType = "MultiFunction"
	SIMULATED DeviceType = "Simulated"
)