/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describes any additional identifiers for a resource.
type Identifier struct {
	// This indicates the world wide, persistent name of the resource.
	DurableName string `json:"DurableName,omitempty"`
	DurableNameFormat DurableNameFormat `json:"DurableNameFormat,omitempty"`
}
